package xyz.btcland.libretube

data class VideoInPlayer(
    val title: String,
    val description: String,
    val uploadDate: String,
    val uploader: String,
    val uploaderUrl: String,
    val uploaderAvatar: String,
    val thumbnailUrl: String,
    val hls: String,
    val uploaderVerified: Boolean,
    val duration: Int,
    val views: Int,
    val likes: Int,
    val dislikes: Int,
    val relatedStreams: List<Video>,
    val livestream: Boolean,
    val proxyUrl: String,
    val audioStreams: List<Stream>,
    val videoStreams: List<Stream>,
    val subtitles: List<Subtitle>

)
data class Stream(
    val url:String,
    val format:String,
    val quality:String,
    val mimeType:String,
    val codec:String,
    val videoOnly: Boolean,
    val bitrate:Int,
    val initStart:Int,
    val initEnd:Int,
    val indexStart:Int,
    val indexEnd:Int,
    val width:Int,
    val height:Int,
    val fps:Int

)

data class Subtitle(
    val url:String,
    val mimeType:String,
    val name:String,
    val code:String,
    val autoGenerated:Boolean
)