package com.github.libretube.helpers

import android.content.Context
import android.view.accessibility.CaptioningManager
import androidx.core.content.getSystemService
import androidx.media3.common.C
import androidx.media3.common.Format
import androidx.media3.common.Tracks
import androidx.media3.common.util.UnstableApi
import androidx.media3.ui.CaptionStyleCompat
import com.github.libretube.R
import com.github.libretube.api.obj.Subtitle
import java.util.Locale

object CaptionHelper {

    const val ROLE_FLAG_AUTO_GEN_SUBTITLE = C.ROLE_FLAG_SUPPLEMENTARY

    @OptIn(UnstableApi::class)
    fun getCaptionStyle(context: Context): CaptionStyleCompat {
        val captioningManager = context.getSystemService<CaptioningManager>()!!
        return if (!captioningManager.isEnabled) {
            CaptionStyleCompat.DEFAULT
        } else {
            CaptionStyleCompat.createFromCaptionStyle(captioningManager.userStyle)
        }
    }

    fun getSubtitleRoleFlags(subtitle: Subtitle?): Int {
        if (subtitle?.code == null) return 0
        return if (subtitle.autoGenerated != true) {
            C.ROLE_FLAG_CAPTION
        } else {
            ROLE_FLAG_AUTO_GEN_SUBTITLE
        }
    }

    fun getCaptionTracks(player: androidx.media3.common.Player) =
        getTracksByType(player, C.TRACK_TYPE_TEXT)

    fun getCurrentPlayedCaptionFormat(player: androidx.media3.common.Player): Format? {
        return getCurrentFormatByTrackType(player, C.TRACK_TYPE_TEXT)
    }

    fun getCurrentVideoFormat(player: androidx.media3.common.Player): Format? {
        return getCurrentFormatByTrackType(player, C.TRACK_TYPE_VIDEO)
    }

    fun getAudioTrackNameFromFormat(
        context: Context,
        audioLanguageAndRoleFlags: Pair<String?, @C.RoleFlags Int>,
    ): String {
        val audioLanguage = audioLanguageAndRoleFlags.first
        return context.getString(R.string.audio_track_format)
            .format(
                if (audioLanguage == null) {
                    context.getString(R.string.unknown_audio_language)
                } else {
                    Locale.forLanguageTag(audioLanguage)
                        .getDisplayName(Locale.getDefault())
                        .ifEmpty { context.getString(R.string.unknown_audio_language) }
                },
                getDisplayAudioTrackType(context, audioLanguageAndRoleFlags.second)
            )
    }

    fun getAudioLanguagesAndRoleFlags(
        groups: List<Tracks.Group>,
        keepOnlySelectedTracks: Boolean
    ): List<Pair<String?, @C.RoleFlags Int>> {
        val trackFilter: (Tracks.Group, Int) -> Boolean = if (keepOnlySelectedTracks) {
            { group, trackIndex -> group.isTrackSupported(trackIndex) && group.isTrackSelected(trackIndex) }
        } else {
            { group, trackIndex -> group.isTrackSupported(trackIndex) }
        }

        return groups.filter { it.type == C.TRACK_TYPE_AUDIO }
            .flatMap { group ->
                (0 until group.length)
                    .filter { trackFilter(group, it) }
                    .map { group.getTrackFormat(it) }
            }
            .map { it.language to it.roleFlags }
            .distinct()
    }

    fun haveAudioTrackRoleFlagSet(@C.RoleFlags roleFlags: Int): Boolean {
        return isFlagSet(roleFlags, C.ROLE_FLAG_DESCRIBES_VIDEO) ||
                isFlagSet(roleFlags, C.ROLE_FLAG_DUB) ||
                isFlagSet(roleFlags, C.ROLE_FLAG_MAIN) ||
                isFlagSet(roleFlags, C.ROLE_FLAG_ALTERNATE)
    }

    fun getFullAudioRoleFlags(roleFlags: Int, acontValue: String): Int {
        val acontRoleFlags = when (acontValue.lowercase()) {
            "dubbed" -> C.ROLE_FLAG_DUB
            "descriptive" -> C.ROLE_FLAG_DESCRIBES_VIDEO
            "original" -> C.ROLE_FLAG_MAIN
            else -> C.ROLE_FLAG_ALTERNATE
        }
        return roleFlags or acontRoleFlags
    }

    private fun getDisplayAudioTrackType(context: Context, @C.RoleFlags roleFlags: Int): String {
        return when {
            roleFlags and C.ROLE_FLAG_DESCRIBES_VIDEO == C.ROLE_FLAG_DESCRIBES_VIDEO ->
                context.getString(R.string.descriptive_audio_track)
            roleFlags and C.ROLE_FLAG_DUB == C.ROLE_FLAG_DUB ->
                context.getString(R.string.dubbed_audio_track)
            roleFlags and C.ROLE_FLAG_MAIN == C.ROLE_FLAG_MAIN ->
                context.getString(R.string.original_or_main_audio_track)
            else -> context.getString(R.string.unknown_audio_track_type)
        }
    }

    private fun getTracksByType(player: androidx.media3.common.Player, trackType: Int): List<Format> {
        val formats = mutableListOf<Format>()
        for (trackGroup in player.currentTracks.groups) {
            if (trackGroup.type != trackType) continue
            for (i in 0 until trackGroup.length) {
                formats.add(trackGroup.getTrackFormat(i))
            }
        }
        return formats
    }

    private fun getCurrentFormatByTrackType(player: androidx.media3.common.Player, trackType: Int): Format? {
        for (trackGroup in player.currentTracks.groups) {
            if (trackGroup.type != trackType) continue
            for (i in 0 until trackGroup.length) {
                if (trackGroup.isTrackSelected(i)) return trackGroup.getTrackFormat(i)
            }
        }
        return null
    }

    private fun isFlagSet(bitField: Int, flag: Int) = bitField and flag == flag
}
