package com.github.libretube.constants

object IntentData {
    const val downloadData = "downloadData"
    const val playerData = "playerData"
    const val id = "id"
    const val videoId = "videoId"
    const val channelId = "channelId"
    const val channelName = "channelName"
    const val playlistId = "playlistId"
    const val timeStamp = "timeStamp"
    const val playlistType = "playlistType"
    const val downloading = "downloading"
    const val openAudioPlayer = "openAudioPlayer"
    const val fragmentToOpen = "fragmentToOpen"
    const val comment = "comment"
    const val minimizeByDefault = "minimizeByDefault"
    const val query = "query"
    const val playlistDescription = "playlistDescription"
    const val playlistName = "playlistName"
    const val shareObjectType = "shareObjectType"
    const val shareData = "shareData"
    const val currentPosition = "currentPosition"
    const val duration = "duration"
    const val updateInfo = "updateInfo"
    const val backupFile = "backupFile"
    const val playlistTask = "playlistTask"
    const val loginTask = "loginTask"
    const val logoutTask = "logoutTask"
    const val color = "color"
    const val streamItem = "streamItem"
    const val url = "url"
    const val videoStats = "videoStats"
}
