name: Build and release app

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*'

jobs:
  build:
    name: Build, sign and release app
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: "17"
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Install Android SDK packages
        run: |
          yes | "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" --licenses >/dev/null || true
          "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" \
            "platform-tools" \
            "platforms;android-36" \
            "build-tools;36.0.0"

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Run release lint
        run: ./gradlew :app:lintRelease --no-daemon

      - name: Run unit tests
        run: ./gradlew :app:testDebugUnitTest --no-daemon

      - name: Build release APK
        run: ./gradlew :app:assembleRelease --no-daemon

      - name: Sign APK
        uses: ilharp/sign-android-release@v2
        id: sign
        with:
          signingKey: ${{ secrets.ANDROID_RELEASE_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_RELEASE_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_RELEASE_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_RELEASE_KEY_PASSWORD }}
          buildToolsVersion: 36.0.0

      - name: Create changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - name: Create changelog summary
        id: changelog-summary
        run: |
          summary_file=$(find fastlane/metadata/android/en-US/changelogs/ | sort -t '/' -k 6n | tail -n 1)
          summary_quoted=$(cat "$summary_file" | xargs -d '\n' -I {} echo "> {}")
          summary=$(echo -e "> [!NOTE]\n> ## Release Highlights\n$summary_quoted")
          echo "summary<<EOF"$'\n'"$summary"$'\n'EOF >> "$GITHUB_OUTPUT"

      - name: Rename APK file
        run: mv "${{ steps.sign.outputs.signedFile }}" "app-release.apk"

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            ${{ steps.changelog-summary.outputs.summary }}

            ${{ steps.changelog.outputs.changes }}
          files: "app-release.apk"
          fail_on_unmatched_files: true
          make_latest: true
